site_name: VISTOPIA
nav: 
   - Home: index.md
   - News: news.md
   - Gits: github.md
   - Essay: essay.md
# Project information
site_description: 'A Material Design theme for MkDocs'
site_author: 'YaBin'
#site_url: 'https://squidfunk.github.io/mkdocs-material/'

# Repository
repo_name: 'vistopia/utopia'
repo_url: 'https://github.com/vistopia/utopia'

# Copyright
copyright: 'Copyright &copy; 2018 - 2019 YaBin Liu'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: 'Playfair Display'
    code: 'Roboto Mono'
# Google Analytics
google_analytics:
  - 'UA-XXXXXXXX-X'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

